### PR TITLE
🐌💙💛

### PR DESCRIPTION
**Pull request by OfficialSkypo**
Ukraine banner version.

### CODE REVIEW

**Comment by Jaccosf** [comment]
Yay! Now let's add it into the menu.

**Comment by Blumlaut** [comment]
we should probably considering rewriting the easter egg function to not have a billion ifelses if we add more..

**Comment by Jaccosf** [comment]
But apart from that, can't this be standard for now?

**Comment by Blumlaut** [comment]
not sure, since easyadmin releases are few and far between, maybe have it on a timer so it clears itself in the future

**Comment by Jaccosf** [comment]
Hmm, good question. Unfortunately we cannot predict when this is done 😢, that would have made it a lot easier...

**Comment by Blumlaut** [comment]
i'll merge this for now, we can discuss how to properly implement this later. i definetely want to add this as an easter egg and revamp the system while we're at it.

**Pull request merged**
