### PR TITLE
Translated rest of menu into Polish

### PR DESCRIPTION
**Pull request by Nimplex**

### CODE REVIEW

**Comment by Blumlaut** [comment]
I'm currently working on adding noclip for 6.0, would you mind if i leave this PR open for now so you can do Polish Translation for the new noclip strings? i reckon i will have finished everything by tomorrow, 6.0 is planned in the coming 2 weeks so there is no hurry 😄 

Thanks for your contribution!

**Comment by Nimplex** [comment]
ofc

**Comment by Blumlaut** [comment]
Cool! Master branch has been updated with the noclip strings now

**Comment by Nimplex** [comment]
done

**Comment by Blumlaut** [comment]
Awesome! Thank you.

**Pull request merged**
