### PR TITLE
update polish translation

### PR DESCRIPTION
**Pull request by kubamaz**

### CODE REVIEW

**Comment by Blumlaut** [comment]
I'm not a native speaker, is there a reason for this specific adjustment? Online Translators seem to claim that both translations are "correct", maybe @Robi321 can provide some feedback?

**Comment by Robi321** [comment]
I am native speaker of Polish and I can say for sure that it is 100 percent correct.
Raport = Zgłoszenie

**Comment by Blumlaut** [comment]
> I am native speaker of Polish and I can say for sure that it is 100 percent correct. Raport = Zgłoszenie

Which one would you say makes more sense in the context? i'm not sure if polish has different dialects, where this _may_ be ambiguous, it would also be nice if @kubamaz could explain the reason for the change.

**Comment by Robi321** [comment]
> > I am native speaker of Polish and I can say for sure that it is 100 percent correct. Raport = Zgłoszenie
> 
> Which one would you say makes more sense in the context? i'm not sure if polish has different dialects, where this _may_ be ambiguous, it would also be nice if @kubamaz could explain the reason for the change.

Raport is like sentence on the course of an event, performance of a task, etc., a report.
Zgłoszenie is an official declaration of adherence to or participation in something, official notice of something

**Comment by Robi321** [comment]
But that change can be merged of course

**Comment by kubamaz** [comment]
> > > I am native speaker of Polish and I can say for sure that it is 100 percent correct. Raport = Zgłoszenie
> > 
> > 
> > Which one would you say makes more sense in the context? i'm not sure if polish has different dialects, where this _may_ be ambiguous, it would also be nice if @kubamaz could explain the reason for the change.
> 
> Raport is like sentence on the course of an event, performance of a task, etc., a report. Zgłoszenie is an official declaration of adherence to or participation in something, official notice of something
exactly

**Pull request merged**
