### PR TITLE
Full dutch translation

### PR DESCRIPTION
**Pull request by Quinten-Gelderland**

### CODE REVIEW

**Comment by Blumlaut** [comment]
i would prefer not having code changes besides translations, also, the additional ban times won't work on non-dutch EasyAdmin Configurations, as their translations are also missing.

**Comment by Quinten-Gelderland** [comment]
If u want i can change the translation for the times to

**Comment by Quinten-Gelderland** [comment]
https://github.com/Blumlaut/EasyAdmin/pull/191 here u go

**Comment by Blumlaut** [comment]
please create one pull request for everything, i can't merge this mess.

**Pull request closed without merging**
